version: '3.8'
services:
  backend:
    image: node:22.2.0
    container_name: backend-condominio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - condominio

  postgres:
    image: postgres:13
    container_name: db-condominio
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: edi2025
      POSTGRES_DB: edicondominio
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - condominio

  nginx:
    image: nginx
    container_name: nginx-condominio
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3333:80"
    depends_on:
      - backend
    networks:
      - condominio

volumes:
  db_data: {}
networks:
  condominio:
    driver: bridge
