version: '3.8'
services:
  backend:
    image: node:22.2.0
    container_name: backend-condominio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - app-edicondominio

  postgres:
    image: postgres:13
    container_name: db-condominio
    environment:
      POSTGRES_USER: edicondominio
      POSTGRES_PASSWORD: edi2025
      POSTGRES_DB: edicondominio
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nginx:
    image: nginx
    container_name: nginx-condominio
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-edicondominio

networks:
  app-edicondominio:
    driver: bridge
