version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - app-edicondominio



  postgres:
    image: postgres:13
    container_name: db-condominio
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: edi2025
      POSTGRES_DB: edicondominio
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - edicondominio

  nginx:
    image: nginx
    container_name: nginx-condominio
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    ports:
      - "3333:80"
    depends_on:
      - backend
    networks:
      - edicondominio

volumes:
  db_data: {}
networks:
  edicondominio:
    driver: bridge
  traefik:
    external: true
